apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-rollout
  labels:
    app: demo-rollout
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo-rollout
  template:
    metadata:
      labels:
        app: demo-rollout
    spec:
      containers:
        - name: demo
          image: nginx:1.25
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: ENV-VAR
              value: "value-2"
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0
      steps:
        - setWeight: 100
